1. Exercise - Descriptive Statistics - Numerical Techniques

Exploring Students’ Performance Dataset - Numerical Techniques

Objective: The objective of this exercise is to practice using numerical techniques to analyze the Students’ Performance dataset and gain insights into the students’ academic performance.

Dataset Description: The Students’ Performance dataset contains information about students’ demographic attributes, such as gender, race/ethnicity, parental education, lunch type, and test scores in three subjects: Math, Reading, and Writing.

Load the Dataset: Import the necessary libraries and load the Students’ Performance dataset into a pandas DataFrame.

In [94]:
import pandas as pd

In [95]:
students_performance = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/prework_data/main/students_performance.csv")

In [96]:
students_performance

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

Explore the Dataset: Use basic pandas functions to get an overview of the dataset, including the number of rows and columns, and number of unique values for each column. For those columns that have less than 10 distinct values, show those unique values. Hint: look at the previous lesson. There you can find the functions or methods you need to use.

In [98]:
students_performance.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [99]:
students_performance.nunique() #utilizamos esta función para ver el número de distintos valores

gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64

In [100]:
datos_categoricos_nominales = ["gender", "race/ethnicity", "lunch",	"test preparation course"] #no siguen una categoría o rango. Los valores tipo sí o no, hombre o mujer, completed/not completed, a pesar de poder considerarse como 0/1 son datos nominales que indican distintos estados y no numéricos
datos_categoricos_ordinales = ["parental level of education"] #representa distintos grados, jerarquía
datos_numéricos_discretos = ["math score", "reading score",	"writing score"] #se podría pensar que las puntuaciones son datos categóricos ordinales, pues representan distintos grados, pero no hay delimitaciones exactas que dividan las categorías. Son numéricos discretos, pues hemos visto que son integers, si fuesen floats tendría infinitos valores y por tanto serían continuos

In [101]:
students_performance.shape #1000 rows, 8 columnas

(1000, 8)

In [102]:
students_performance["gender"]

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [103]:
students_performance.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [104]:
students_performance["gender"].unique() #con la función .unique() vemos los valores únicos de una columna

array(['female', 'male'], dtype=object)

In [105]:
students_performance.columns[1]

'race/ethnicity'

In [106]:
students_performance.iloc[:, 1].unique()

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [107]:
students_performance["parental level of education"].unique()

array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)

In [108]:
students_performance["parental level of education"].nunique()

6

In [109]:
students_performance["lunch"].unique()

array(['standard', 'free/reduced'], dtype=object)

In [110]:
students_performance["test preparation course"].unique()

array(['none', 'completed'], dtype=object)

In [111]:
students_performance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB



Analyze Descriptive Statistics: Calculate and interpret descriptive statistics, including measures of central tendency (mean, median, mode) and dispersion (standard deviation, range) for the numerical variables, and frequency counts for categorical variables.

In [113]:
students_performance.describe() #con este método podemos ver el count o número de valores para esa columna, el mean y meadian (50%), std y otros valores

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [114]:
students_performance["math score"].mode() #con esta función obtener el valor que más se repite

0    65
Name: math score, dtype: int64

In [115]:
students_performance["math score"].mean()

66.089

In [116]:
students_performance["math score"].min()

0

In [117]:
students_performance["math score"].max()

100

In [118]:
students_performance["reading score"].mode()

0    72
Name: reading score, dtype: int64

In [119]:
students_performance["reading score"].mean()

69.169

In [120]:
students_performance["writing score"].mode()

0    74
Name: writing score, dtype: int64

In [121]:
students_performance["writing score"].mean()

68.054

In [122]:
students_performance["math score"].std() #La desviación estándar mide la cantidad de variación o dispersión de un conjunto de valores

15.163080096009468

In [123]:
numerical_columns = students_performance.select_dtypes(include='number') #utilizamos esta función para seleccionar varias columnas según su dtype o tipo de dato

In [124]:
numerical_columns.std()

math score       15.163080
reading score    14.600192
writing score    15.195657
dtype: float64

In [125]:
rango = numerical_columns.max() - numerical_columns.min()
print(rango)

math score       100
reading score     83
writing score     90
dtype: int64

In [126]:
#como podemos ver con la función anterior .describe(), los valores máximos son 100 y el minimo desde 17 hasta 0. El rango es la diferencia entre ambos

In [127]:
students_performance["reading score"].count() #hay mil valores para esta columna

1000

In [128]:
students_performance["reading score"].value_counts()

reading score
72    34
74    33
64    32
67    30
73    30
      ..
28     1
26     1
17     1
32     1
40     1
Name: count, Length: 72, dtype: int64

In [129]:
#hay 72 valores únicos, el que más se repite o moda es el 72 (34 veces)

In [130]:
students_performance["parental level of education"].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [131]:
#usamos esta función contadora de frecuencias en los datos categóricos de la misma manera